# Chybějící hodnoty

Stáhneme si soubory, se kterými budeme pracovat.

Vytvoříme pandas DataFrame pro soubory s výsledky maturitní zkoušky.

In [1]:
import pandas

In [2]:
u202 = pandas.read_csv("../../data/u202.csv")
u203 = pandas.read_csv("../../data/u203.csv")
u302 = pandas.read_csv("../../data/u302.csv")

Podíváme se na data.

In [3]:
u202

    cisloStudenta           predmet  znamka den
0               1            Chemie     NaN  pá
1               2           Dějepis     3.0  pá
2               3        Matematika     2.0  út
3               2  Společenské vědy     2.0  pá
4               4          Biologie     1.0  pá
5               5           Dějepis     1.0  po
6               6            Fyzika     2.0  čt
7               7           Dějepis     4.0  po
8               8        Matematika     2.0  po
9               9           Dějepis     NaN  pá
10             10            Chemie     2.0  st
11              3            Chemie     5.0  út
12             11        Matematika     1.0  st
13             12          Biologie     4.0  st
14             10           Dějepis     5.0  st

## Práce s chybějícími hodnotami
anglicky _missing values_


**Co je chybějící hodnota?**
- hodnota `NaN` (Not a Number)
    - _napr. prazdna bunka v csv --> rovnou nahrazena NaN_
- `None` = zabudovaná konstanta v Pythonu 
- `pd.NA` = zatím experiment hodnota, která by měla reprezentovat chybějící hodnoty všech typů

<br>
<br>

**Co není chybějící hodnota?**
- řetězec `''` nebo `'NaN'` and `'None'`
- `inf` / `-inf` = infinity je nedefinované číslo, kladné nebo záporné

<br>
<br>

**Jak s chybějící hodnotou zacházet?**
1. Nejlepší je vždy ověření, proč údaje chybí (např. u poskytovatele dat) a pokud je to možné, zajistit jejich doplnění.
2. Nahradit chybějící hodnoty jinými hodnotami.
3. Odstranit všechny řádky s chybějícími daty z datového setu.
4. Vyčlenit je do separátního datasetu a zpracovat je zvlášť.

_Důležité je mít na paměti, že vyřazením některých řádků může dojít ke zkreslení výsledků analýzy!_

## Jak chybějící hodnoty najít

**`isnull()`** 

**`notnull()`**

Obě metody vrací hodnoty `True` nebo `False`

Vyzkoušíme si `isnull()`.

In [4]:
u202["znamka"].isnull()

## Alternativa
# u202['znamka'].isna() # isna() se NIJAK neliší od isnull()

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
Name: znamka, dtype: bool

Vyzkoušíme si `notnull()`.

In [5]:
u202["znamka"].notnull()

## Alternativa
# u202['znamka'].notna()

0     False
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9     False
10     True
11     True
12     True
13     True
14     True
Name: znamka, dtype: bool

Vybereme pomocí `isnull()` jen řádky, které mají chybějící hodnoty.

In [6]:
## Najedeme je ty, kde isnull() je True
jen_null_radky = u202[u202["znamka"].isnull()]
jen_null_radky

   cisloStudenta  predmet  znamka den
0              1   Chemie     NaN  pá
9              9  Dějepis     NaN  pá

## Jak chybějící hodnoty odstranit nebo nahradit


**`dropna()`**
- vrátí datový set očištěn od chybějících dat
- `dropna(axis=0)` --> odstraní všechny řádky, které obsahují chybějící data
- `dropna(axis=1)` --> odstraní všechny sloupce, které obsahují chybějící data
- Dokumentace: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html
<br>
<br>


**`fillna(x)`**
- nahradí všechna chybějící data a hodnoty hodnotou x
- Dokumentace: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html

In [7]:
## Příklady těchto metod - pojďme si to vyzkoušet
testovaci_data = u202[u202["znamka"].isnull()]
testovaci_data

   cisloStudenta  predmet  znamka den
0              1   Chemie     NaN  pá
9              9  Dějepis     NaN  pá

In [8]:
# Odstranění řádků s dropna()
testovaci_data.dropna()

## Alternativa
# testovaci_data.dropna(axis=0)

Empty DataFrame
Columns: [cisloStudenta, predmet, znamka, den]
Index: []

In [9]:
# Odstranění sloupců s dropna()
testovaci_data.dropna(axis=1)

   cisloStudenta  predmet den
0              1   Chemie  pá
9              9  Dějepis  pá

In [10]:
# Nahrazení chybějících hodnot
testovaci_data.fillna("Hodnota chybí")

   cisloStudenta  predmet         znamka den
0              1   Chemie  Hodnota chybí  pá
9              9  Dějepis  Hodnota chybí  pá