# Agregace dat

Stáhneme si soubory, se kterými budeme pracovat.

Vytvoříme pandas DataFrame pro soubory s výsledky maturitní zkoušky.

In [16]:
import pandas

Finální tabulku, kterou jsme právě vytvořili, si můžete pro kontrolu stáhnout zde: 

<https://kodim.cz/cms/assets/analyza-dat/python-data-1/python-pro-data-1/agregace-a-spojovani/pokrocile-upravy/maturita.csv>

In [17]:
maturita = pandas.read_csv(
    "https://kodim.cz/cms/assets/analyza-dat/python-data-1/python-pro-data-1/agregace-a-spojovani/pokrocile-upravy/maturita.csv"
)
maturita.head()

   cisloStudenta           predmet  znamka den mistnost
0              2           Dějepis     3.0  pá     u202
1              3        Matematika     2.0  út     u202
2              2  Společenské vědy     2.0  pá     u202
3              4          Biologie     1.0  pá     u202
4              5           Dějepis     1.0  po     u202

**metoda `groupby()`**

Pomocí metody groupby vyrobíme z `DataFrame` speciální objekt `DataFrameGroupBy`. 

`maturita.groupby('mistnost')`

**Agregační funkce**

In [18]:
maturita.groupby("mistnost").count()

          cisloStudenta  predmet  znamka  den
mistnost
u202                 13       13      13   13
u203                 13       13      13   13
u302                 12       12      12   12

Další užitečné agregační funkce jsou například:

* `sum` - součet hodnot,
* `max` - maximální hodnota,
* `min` - minimální hodnota,
* `first` - první hodnota,
* `last` - poslední hodnota,
* `mean` - průměr z hodnot,
* `median` - medián z hodnot.

![Princip agragace](../../img/groupby.png)

**Agregace vybraných sloupců**

In [19]:
maturita.groupby("predmet")["znamka"].mean()

predmet
Biologie            2.750000
Chemie              3.800000
Dějepis             3.200000
Fyzika              2.800000
Informatika         2.333333
Matematika          2.714286
Společenské vědy    2.250000
Zeměpis             2.000000
Name: znamka, dtype: float64

In [21]:
## Nebo více sloupců
maturita.groupby("predmet")[["znamka", "cisloStudenta"]].mean()

                    znamka  cisloStudenta
predmet
Biologie          2.750000      13.250000
Chemie            3.800000      10.400000
Dějepis           3.200000       7.600000
Fyzika            2.800000      13.800000
Informatika       2.333333      15.500000
Matematika        2.714286      11.142857
Společenské vědy  2.250000      11.250000
Zeměpis           2.000000      15.000000

In [22]:
maturita.groupby(["predmet", "den"])[["znamka"]].mean()

                        znamka
predmet          den
Biologie         pá   1.000000
                 st   4.000000
                 út   2.000000
Chemie           po   4.000000
                 pá   3.000000
                 st   3.500000
                 út   5.000000
Dějepis          po   2.500000
                 pá   3.000000
                 st   4.000000
Fyzika           po   4.000000
                 st   3.000000
                 čt   2.000000
Informatika      po   2.000000
                 pá   1.000000
                 st   4.000000
                 út   2.500000
Matematika       po   3.333333
                 st   1.000000
                 út   2.000000
                 čt   3.000000
Společenské vědy po   2.000000
                 pá   2.500000
Zeměpis          po   1.000000
                 út   3.000000

**ČTENÍ NA DOMA**

**Funkce `.agg()`**

Dokumentace: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.agg.html

In [23]:
maturita.groupby("cisloStudenta").agg({"znamka": ["max", "mean"]})

              znamka
                 max mean
cisloStudenta
2                3.0  2.5
3                5.0  3.5
4                1.0  1.0
5                3.0  2.0
6                5.0  3.5
7                4.0  3.5
8                2.0  1.5
10               5.0  3.5
11               5.0  3.0
12               4.0  3.5
13               5.0  4.5
14               3.0  3.0
15               3.0  3.0
16               2.0  2.0
17               4.0  3.5
20               2.0  1.5
21               4.0  4.0
22               3.0  3.0
23               1.0  1.0

In [24]:
## Řazení hodnot v DataFramu s Multiindexem

vysledky_studenty = maturita.groupby("cisloStudenta").agg({"znamka": ["max", "mean"]})
vysledky_studenty.sort_values([("znamka", "mean")], ascending=False)

              znamka
                 max mean
cisloStudenta
13               5.0  4.5
21               4.0  4.0
12               4.0  3.5
6                5.0  3.5
7                4.0  3.5
17               4.0  3.5
10               5.0  3.5
3                5.0  3.5
15               3.0  3.0
22               3.0  3.0
11               5.0  3.0
14               3.0  3.0
2                3.0  2.5
16               2.0  2.0
5                3.0  2.0
8                2.0  1.5
20               2.0  1.5
4                1.0  1.0
23               1.0  1.0

## Co vlastně umí série

Série umí například sama spočítat svůj součet a vrátit výsledek jako číslo. 

Dokumentace: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html

In [28]:
staty = pandas.read_json("../../data/staty.json")
staty.head()

,name,alpha2Code,alpha3Code,capital,region,subregion,population,area,gini
0,Afghanistan,AF,AFG,Kabul,Asia,Southern Asia,27657145,652230.0,27.8
1,Åland Islands,AX,ALA,Mariehamn,Europe,Northern Europe,28875,1580.0,NaN
2,Albania,AL,ALB,Tirana,Europe,Southern Europe,2886026,28748.0,34.5
3,Algeria,DZ,DZA,Algiers,Africa,Northern Africa,40400000,2381741.0,35.3
4,American Samoa,AS,ASM,Pago Pago,Oceania,Polynesia,57100,199.0,NaN

In [29]:
staty["population"].sum()

7349137231

In [ ]:
populace = staty["population"]

print(f"Prumer je {populace.mean()}.")
print(f"Minumum je {populace.min()}.")
print(f"Maximum je {populace.max()}.")
print(f"Median je {populace.median()}.")

Prumer je 29396548.924.
Minumum je 0.
Maximum je 1377422166.
Median je 4648733.5.