## Řazení

**Metoda `sort_values`**

Metoda `sort_values` standardně řadí vzestupně. 

Chceme-li řadit sestupně, zadáme jí parametr `ascending` a nastavíme ho na `False`.

In [2]:
import pandas

maturita = pandas.read_csv("../../data/maturita.csv")

In [3]:
## Řazení hodnot v Series
## https://pandas.pydata.org/docs/reference/api/pandas.Series.sort_values.html

vysledky_predmetu = maturita.groupby("predmet")["znamka"].max()
vysledky_predmetu.sort_values(ascending=False)

predmet
Chemie              5.0
Dějepis             5.0
Matematika          5.0
Biologie            4.0
Fyzika              4.0
Informatika         4.0
Společenské vědy    3.0
Zeměpis             3.0
Name: znamka, dtype: float64

In [4]:
## Řazení hodnot v DataFramu
## https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html

maturita.sort_values(by="znamka")

    cisloStudenta           predmet  znamka den mistnost
31             20        Matematika     1.0  čt     u302
26             23       Informatika     1.0  po     u302
3               4          Biologie     1.0  pá     u202
4               5           Dějepis     1.0  po     u202
27             23  Společenské vědy     1.0  po     u302
29              4       Informatika     1.0  pá     u302
10             11        Matematika     1.0  st     u202
20              8           Zeměpis     1.0  po     u203
23             20            Fyzika     2.0  čt     u203
30             16          Biologie     2.0  út     u302
19             16       Informatika     2.0  út     u203
7               8        Matematika     2.0  po     u202
5               6            Fyzika     2.0  čt     u202
2               2  Společenské vědy     2.0  pá     u202
1               3        Matematika     2.0  út     u202
8              10            Chemie     2.0  st     u202
34             14           Dějepis     3.0  st     u302
25             22           Zeměpis     3.0  út     u203
22             15  Společenské vědy     3.0  pá     u203
0               2           Dějepis     3.0  pá     u202
18             15            Chemie     3.0  pá     u203
37             17        Matematika     3.0  po     u302
17             14            Fyzika     3.0  st     u203
16             12            Fyzika     3.0  st     u203
15              7       Informatika     3.0  po     u203
13              5  Společenské vědy     3.0  po     u203
36             22       Informatika     3.0  út     u302
35             13            Chemie     4.0  po     u302
6               7           Dějepis     4.0  po     u202
32             21       Informatika     4.0  st     u302
21             17            Fyzika     4.0  po     u203
24             21          Biologie     4.0  st     u203
11             12          Biologie     4.0  st     u202
9               3            Chemie     5.0  út     u202
28              6        Matematika     5.0  čt     u302
33             11            Chemie     5.0  st     u302
14             13        Matematika     5.0  po     u203
12             10           Dějepis     5.0  st     u202

In [5]:
## Řazení hodnot v DataFramu s Multiindexem

vysledky_studenty = maturita.groupby("cisloStudenta").agg({"znamka": ["mean"]})
vysledky_studenty.sort_values([("znamka", "mean")])

              znamka
                mean
cisloStudenta
23               1.0
4                1.0
20               1.5
8                1.5
5                2.0
16               2.0
2                2.5
11               3.0
22               3.0
14               3.0
15               3.0
10               3.5
6                3.5
17               3.5
3                3.5
7                3.5
12               3.5
21               4.0
13               4.5