# Načtení dat s využitím knihovny pandas

## Základní práce s DataFrame

Základní datový typ, který Pandas nabízí, je `DataFrame`, neboli lidově „tabulka”. 

Jednotlivé záznamy jsou v ní uvedeny jako řádky a části těchto záznamů jsou úhledně srovnány ve sloupcích.

Dokumentace: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

In [ ]:
print("neco")

:

In [ ]:
import pandas

# vytvoreni prazdneho dataframe objektu
df_empty = pandas.DataFrame()
print(df_empty)

:

In [3]:
# vytvoreni prazdneho dataframe objektu s nazvy sloupcu
df_with_columns = pandas.DataFrame(columns=["column1", "column2", "column3"])
print(df_with_columns)

Empty DataFrame
Columns: [column1, column2, column3]
Index: []

## Načítání dat

**Funkce `read_csv()`** 

Dokumentace: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

Pandas nabízí kromě funkce `read_csv()` také funkci pro čtení formátu JSON `read_json()` nebo dokonce funkci pro čtení přímo Excelových tabulek `read_excel()`.

**Načtení csv souboru**

Důležité je, že si soubor musíš uložit nebo zkopírovat do stejného adresáře, v jakém právě pracuješ ve Visual Studiu.

In [4]:
url = "https://kodim.cz/cms/assets/analyza-dat/python-data-1/python-pro-data-1/nacteni-dat/nacteni-dat/nakupy.csv"

In [32]:
# Stazeni souboru nakupy.csv
# import requests

# requests.packages.urllib3.disable_warnings()

# r = requests.get(url, allow_redirects=True, verify=False)
# open("nakupy.csv", "wb").write(r.content)

In [29]:
# Nahrani primo z webu
nakupy = pandas.read_csv(url)

In [ ]:

# Nahrani lokalniho souboru
nakupy = pandas.read_csv("../../../data/nakupy.csv")

### Index

Index je hodnota, která identifikuje řádek. 

V některých případech nemusíme jako index používat číslo řádku, ale můžeme jako index vybrat některý ze sloupců. Obdobnou funkci má v databázích primární klíč.

### Základní informace o tabulce

Metoda `info()` vrací souhrnné informace o celé tabulce: názvy sloupců, datové typy, počet neprázdných hodnot atd.

In [7]:
nakupy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   jmeno   11 non-null     object
 1   datum   11 non-null     object
 2   vec     11 non-null     object
 3   cena    11 non-null     int64
dtypes: int64(1), object(3)
memory usage: 480.0+ bytes

Počet řádků a sloupců můžeme získat z vlastnosti `shape`.

Můžeme si z ní data načíst stejně jako ze seznamu, na prvním místě je vždy počet řádků a na druhém počet sloupců.

In [8]:
# Pokud by nás třeba zajímal jen počet řádků, napíšeme:
pocet_radku = nakupy.shape[0]
print("Moje data mají " + str(pocet_radku) + " řádků.")

Moje data mají 11 řádků.


Názvy všech sloupců získáme pomocí vlastnosti `columns`.

In [33]:
nakupy.columns

Index(['jmeno', 'datum', 'vec', 'cena'], dtype='object')

## Výběr sloupců

Pokud vybíráme pouze jeden sloupec, vrátí se nám takzvaná Série (`Series`), což je jiný datový typ než `DataFrame`. 

Sérii si představme jako jednorozměrnou tabulku.

In [10]:
nakupy["vec"]

0         Prací prášek
1                 Savo
2       Toaletní papír
3                 Pivo
4     Pytel na odpadky
5     Utěrky na nádobí
6       Toaletní papír
7         Pečící papír
8                 Savo
9                Máslo
10                Káva
Name: vec, dtype: object

Pro výběr více sloupců musíme do indexace DataFrame vložit seznam s názvy sloupců.

In [11]:
nakupy[["jmeno", "cena"]]

    jmeno  cena
0    Petr   399
1   Ondra    80
2    Petr    65
3   Libor   124
4    Petr    75
5    Míša   130
6   Ondra   120
7    Míša    30
8   Zuzka    80
9   Pavla    50
10  Ondra   300

In [12]:
# Tady se nám již vrátil datový typ DataFrame.
# Tohoto triku můžeme využít, když
# - chceme získat pouze jeden sloupec,
# - ale nechceme ho v datovém typu Série,
# - ale jako DataFrame.

nakupy[["vec"]]

                 vec
0       Prací prášek
1               Savo
2     Toaletní papír
3               Pivo
4   Pytel na odpadky
5   Utěrky na nádobí
6     Toaletní papír
7       Pečící papír
8               Savo
9              Máslo
10              Káva

### Začátek a konec jinak

K zobrazení posledních několik řádků můžeme použít i funkce `head()` a `tail()`.

In [13]:
nakupy.head()  # nakupy.head(10) zobrazi 10 prvnich radek

   jmeno       datum               vec  cena
0   Petr  2020-02-05      Prací prášek   399
1  Ondra  2020-02-08              Savo    80
2   Petr  2020-02-24    Toaletní papír    65
3  Libor  2020-03-05              Pivo   124
4   Petr  2020-03-18  Pytel na odpadky    75

In [34]:
nakupy.tail()

    jmeno       datum             vec  cena
6   Ondra  2020-04-22  Toaletní papír   120
7    Míša  2020-05-05    Pečící papír    30
8   Zuzka  2020-06-05            Savo    80
9   Pavla  2020-06-13           Máslo    50
10  Ondra  2020-07-25            Káva   300

---
# Bonus

## Výběr řádků

### Výběr řádků pomocí čísla řádku

V `pandas` má každý řádek přiřazený _index_. 

Jako _index_ můžeme zvolit některý ze sloupců. 

Pokud však tabulku načteme bez toho, abychom specifikovali _index_, pandas nám vytvoří číselný _index_ automaticky.

K vybrání jednoho konkrétního řádku můžeme použít metodu `iloc[]`.

In [14]:
# Zkusme si zobrazit třeba čtvrtý nákup.
nakupy.iloc[3]

# Výběr jednoho řádku nám vrátí Sérii stejně jako v případě výběru jediného sloupce.

jmeno         Libor
datum    2020-03-05
vec            Pivo
cena            124
Name: 3, dtype: object

Metoda `iloc[]` umožňuje pro výběr řádků použít rozsah ve formátu **od:do**. 

K tomu používáme dvojtečku. Před dvojtečku píšeme první řádek, který chceme vypsat a za dvojtečku první řádek, který již vy výpisu nebude.

In [15]:
nakupy.iloc[3:5]

# nakupy.iloc[:3] ## prvni tri radky
# nakupy.iloc[8:] ## posledni tri radky
# nakupy.iloc[-3:] ## posledni tri radky

   jmeno       datum               vec  cena
3  Libor  2020-03-05              Pivo   124
4   Petr  2020-03-18  Pytel na odpadky    75

## Výběr řádků a sloupců podle čísla

Čísla sloupců zadáváme jako druhý parametr funkce `iloc`.

In [16]:
nakupy.iloc[:5, 0]

0     Petr
1    Ondra
2     Petr
3    Libor
4     Petr
Name: jmeno, dtype: object

Pro zobrazení nesousedících sloupců (nebo řádků) použijeme _seznam_.

In [17]:
nakupy.iloc[:5, [0, 3]]

   jmeno  cena
0   Petr   399
1  Ondra    80
2   Petr    65
3  Libor   124
4   Petr    75

Pro výběr všech řádků napíšeme jako první parametr pouze dvojtečku.

In [18]:
nakupy.iloc[:, [0, 3]]

    jmeno  cena
0    Petr   399
1   Ondra    80
2    Petr    65
3   Libor   124
4    Petr    75
5    Míša   130
6   Ondra   120
7    Míša    30
8   Zuzka    80
9   Pavla    50
10  Ondra   300

In [38]:
# Neco navíc: Cesta z DataFrame do CSV

nakupy.to_csv("../../../data/nakupy_export.csv", sep=",", encoding="utf-8", index=False)

## DOKUMENTACE: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html